name: Build on push master

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: avinakefin/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: avinakefin/build-kernel@master
      id: build
      env:
        NAME: Samsoe
      with:
        arch: arm64
        compiler: gcc/10
        defconfig: ginkgo_defconfig
        image: Image.gz-dtb
        dtbo: dtbo.img

